"""
Noise generators.

Every generator takes an explicit :class:`numpy.random.Generator` and
returns a ``(T, N)`` array. Pink noise is generated by spectral shaping in
the frequency domain (Timmer & König 1995).
"""

from __future__ import annotations

from collections.abc import Callable
from typing import Literal

import numpy as np

from diaxcondel._rng import RNGLike, as_generator
from diaxcondel._typing import FloatArray

NoiseFn = Callable[[int, int, float, RNGLike], FloatArray]
"""Type alias: ``(n_nodes, n_samples, sample_rate_hz, rng) -> (T, N) array``."""


def white_noise(n_nodes: int, n_samples: int, sample_rate_hz: float, rng: RNGLike, *, std: float = 1.0) -> FloatArray:
    """
    Generate independent white Gaussian noise.

    Parameters
    ----------
    n_nodes : int
        Number of nodes.
    n_samples : int
        Number of time samples.
    sample_rate_hz : float
        Sampling rate. Used to scale variance so that integrated power per
        unit time is independent of sample rate.
    rng : RNGLike
        Random generator or seed.
    std : float
        Per-node standard deviation (after sample-rate scaling).

    Returns
    -------
    FloatArray of shape (n_samples, n_nodes)
        White noise with variance ``std**2 * sample_rate_hz`` per sample.
    """
    gen = as_generator(rng)
    out = gen.standard_normal(size=(n_samples, n_nodes))
    return out * (std * np.sqrt(sample_rate_hz))


def pink_noise(n_nodes: int, n_samples: int, sample_rate_hz: float, rng: RNGLike, *, std: float = 1.0) -> FloatArray:
    """
    Generate independent 1/f (pink) Gaussian noise via spectral shaping.

    Parameters
    ----------
    n_nodes : int
        Number of nodes.
    n_samples : int
        Number of time samples.
    sample_rate_hz : float
        Sampling rate. Sets the frequency grid.
    rng : RNGLike
        Random generator or seed.
    std : float
        Per-node target standard deviation.

    Returns
    -------
    FloatArray of shape (n_samples, n_nodes)
        Pink noise normalised to the requested standard deviation.

    Notes
    -----
    Implements the Timmer & König (1995) approach: draw white-noise
    spectral coefficients, scale by ``1 / sqrt(f)``, inverse-FFT.
    Sample-rate agnostic.
    """
    gen = as_generator(rng)
    # Frequency grid (one-sided rfft).
    freqs = np.fft.rfftfreq(n_samples, d=1.0 / sample_rate_hz)
    scale = np.zeros_like(freqs)
    nz = freqs > 0
    scale[nz] = 1.0 / np.sqrt(freqs[nz])
    scale[0] = 0.0  # zero DC
    # Complex Gaussian coefficients.
    re = gen.standard_normal(size=(freqs.size, n_nodes))
    im = gen.standard_normal(size=(freqs.size, n_nodes))
    coefs = (re + 1j * im) * scale[:, None]
    out = np.fft.irfft(coefs, n=n_samples, axis=0)
    # Normalise per channel so each has time-domain variance s^2 * fs,
    # matching white_noise. The post-irfft normalisation removes the
    # arbitrary scale of the random spectral coefficients; we then scale
    # to the target sample-rate-dependent variance.
    out = (out - out.mean(axis=0, keepdims=True)) / out.std(axis=0, keepdims=True)
    return out * (std * np.sqrt(sample_rate_hz))


def colored_noise(
    n_nodes: int,
    n_samples: int,
    sample_rate_hz: float,
    rng: RNGLike,
    *,
    std: float = 1.0,
    exponent: float = 1.0,
) -> FloatArray:
    """
    Generate independent Gaussian noise with a ``1 / f**exponent`` spectrum.

    Parameters
    ----------
    n_nodes : int
        Number of nodes.
    n_samples : int
        Number of time samples.
    sample_rate_hz : float
        Sampling rate. Sets the frequency grid.
    rng : RNGLike
        Random generator or seed.
    std : float
        Per-node target standard deviation.
    exponent : float
        Spectral exponent ``alpha`` in ``S(f) ~ 1 / f**alpha``. ``0`` is
        white, ``1`` pink, ``2`` brown.

    Returns
    -------
    FloatArray of shape (n_samples, n_nodes)
        Noise normalised to the requested standard deviation.

    Notes
    -----
    Spectral shaping follows Timmer & König (1995): draw white-noise
    spectral coefficients, scale their amplitude by ``f ** (-alpha / 2)``,
    and inverse-FFT. The DC component is set to zero, so the output has zero
    mean regardless of the exponent.
    """
    gen = as_generator(rng)
    freqs = np.fft.rfftfreq(n_samples, d=1.0 / sample_rate_hz)
    scale = np.zeros_like(freqs)
    nz = freqs > 0
    scale[nz] = freqs[nz] ** (-0.5 * exponent)
    scale[0] = 0.0
    re = gen.standard_normal(size=(freqs.size, n_nodes))
    im = gen.standard_normal(size=(freqs.size, n_nodes))
    coefs = (re + 1j * im) * scale[:, None]
    out = np.fft.irfft(coefs, n=n_samples, axis=0)
    spread = out.std(axis=0, keepdims=True)
    spread = np.where(spread > 0, spread, 1.0)
    out = (out - out.mean(axis=0, keepdims=True)) / spread
    return out * (std * np.sqrt(sample_rate_hz))


def correlated_noise(
    n_nodes: int,
    n_samples: int,
    sample_rate_hz: float,
    rng: RNGLike,
    *,
    std: float = 1.0,
    correlation: float = 0.5,
    exponent: float = 0.0,
) -> FloatArray:
    """
    Generate Gaussian noise shared to a chosen degree across regions.

    Independent inputs are a strong assumption: any coherence between two
    regions then has to come from the connections. Real drive is partly
    shared — common subcortical input, common reference — and shared input
    produces coherence on its own. Varying ``correlation`` separates the two
    explanations.

    Parameters
    ----------
    n_nodes : int
        Number of nodes.
    n_samples : int
        Number of time samples.
    sample_rate_hz : float
        Sampling rate.
    rng : RNGLike
        Random generator or seed.
    std : float
        Per-node standard deviation, on the same scale as
        :func:`white_noise`.
    correlation : float
        Fraction of each node's input variance that is common to all nodes,
        in ``[0, 1]``. The input correlation between any two nodes equals it
        exactly: ``0`` reproduces independent noise, ``1`` drives every
        region with the same signal.
    exponent : float
        Spectral slope of both the shared and the independent part, as in
        :func:`colored_noise`. ``0`` is white.

    Returns
    -------
    FloatArray of shape (n_samples, n_nodes)
        Noise whose per-node variance matches :func:`white_noise` and whose
        pairwise correlation is ``correlation``.
    """
    if not 0.0 <= correlation <= 1.0:
        raise ValueError("correlation must lie in [0, 1]")
    gen = as_generator(rng)
    draw = white_noise if exponent == 0.0 else colored_noise
    kwargs: dict[str, float] = {} if exponent == 0.0 else {"exponent": exponent}
    independent = draw(n_nodes, n_samples, sample_rate_hz, gen, std=std, **kwargs)  # type: ignore[operator]
    shared = draw(1, n_samples, sample_rate_hz, gen, std=std, **kwargs)  # type: ignore[operator]
    # Variances add, so the weights are square roots and the marginal
    # variance is unchanged whatever the correlation.
    return np.sqrt(1.0 - correlation) * independent + np.sqrt(correlation) * shared


def get_noise_fn(strategy: Literal["white", "pink", "colored", "correlated"], **kwargs: float) -> NoiseFn:
    """
    Return a configured noise function by name.

    Parameters
    ----------
    strategy : {"white", "pink", "colored", "correlated"}
        Noise colour. ``"colored"`` takes an ``exponent`` keyword;
        ``"correlated"`` also takes a ``correlation``.
    **kwargs
        Keyword arguments forwarded to the underlying generator (e.g. ``std``).

    Returns
    -------
    NoiseFn
        Callable ``(n_nodes, n_samples, sample_rate_hz, rng) -> (T, N)``.
    """
    if strategy == "white":
        return lambda n, t, fs, rng: white_noise(n, t, fs, rng, **kwargs)
    if strategy == "pink":
        return lambda n, t, fs, rng: pink_noise(n, t, fs, rng, **kwargs)
    if strategy == "colored":
        return lambda n, t, fs, rng: colored_noise(n, t, fs, rng, **kwargs)
    if strategy == "correlated":
        return lambda n, t, fs, rng: correlated_noise(n, t, fs, rng, **kwargs)
    raise ValueError(f"unknown noise strategy {strategy!r}")
